short_environment = "dev"
location = "UK South"
environment = "Development"
integrations_hostname = "https://dev-integrations.airslip.com"
shopify_redirecturi = "https://dev-integrations.airslip.com/oauth/v1/auth/callback/Shopify"